#!/bin/bash

mkdir -p /tmp/bitnami/pkg/cache/
cd /tmp/bitnami/pkg/cache/ || exit
COMPONENTS=( \
      "python-3.9.18-2-linux-${OS_ARCH}-debian-11" \
      "wait-for-port-1.0.6-13-linux-${OS_ARCH}-debian-11" \
      "ruby-3.0.6-5-linux-${OS_ARCH}-debian-11" \
      "redis-client-7.0.13-0-linux-${OS_ARCH}-debian-11" \
      "postgresql-client-15.4.0-1-linux-${OS_ARCH}-debian-11" \
      "node-16.20.2-1-linux-${OS_ARCH}-debian-11" \
    )
for COMPONENT in "${COMPONENTS[@]}"; do
  if [ ! -f "${COMPONENT}.tar.gz" ]; then
    curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz" -O ;
    curl -SsLf "https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz.sha256" -O ;
  fi
  sha256sum -c "${COMPONENT}.tar.gz.sha256"
  tar -zxf "${COMPONENT}.tar.gz" -C /opt/bitnami --strip-components=2 --no-same-owner --wildcards '*/files'
  rm -rf "${COMPONENT}".tar.gz{,.sha256} ;
done